name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS EKS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Setup kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --name fintech-eks --region us-east-1

    - name: Deploy to EKS
      run: |
        kubectl apply -f eks-deployment.yaml
        kubectl apply -f eks-service.yaml

